name = input("Hello, what's your name?")
print(f'Your name is {name}')
number = input("What's your lucky number?")
print(f'Your lucky number is {int(number)}, the double is {int(number)*2}')
h = input("Say hello")
print(f'{h+h}')
a = input("Give me a float number")
print(f'{float(a)/3.5}')